version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:6.2.7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis 
    volumes:
      - .:/burning_house
volumes:
  mysql_data:
  redis_data:
