version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
  app:
    build:
      context: .
    command: "irb"
    depends_on:
      - db
      - redis 
    tty: true
    stdin_open: true
    volumes:
    - .:/burning_house
  redis:
    image: redis:6.2.7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data:
